// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null

    this._missing = 5
  }

  add (name, handler) {
    switch (name) {
      case '@autopass-namespace/removeWriter':
        this._handler0 = handler
        break
      case '@autopass-namespace/addWriter':
        this._handler1 = handler
        break
      case '@autopass-namespace/put':
        this._handler2 = handler
        break
      case '@autopass-namespace/del':
        this._handler3 = handler
        break
      case '@autopass-namespace/addInvite':
        this._handler4 = handler
        break
      default:
        throw new Error('Cannot register a handler for a nonexistent route: ' + name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@autopass-namespace/removeWriter"')
    assert(this._handler1 !== null, 'Missing handler for "@autopass-namespace/addWriter"')
    assert(this._handler2 !== null, 'Missing handler for "@autopass-namespace/put"')
    assert(this._handler3 !== null, 'Missing handler for "@autopass-namespace/del"')
    assert(this._handler4 !== null, 'Missing handler for "@autopass-namespace/addInvite"')
  }

  async dispatch (encoded, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    const state = { buffer: encoded, start: 0, end: encoded.byteLength }
    const id = c.uint.decode(state)

    setVersion(defaultVersion)

    switch (id) {
      case 0:
        return this._handler0(route0.enc.decode(state), context)
      case 1:
        return this._handler1(route1.enc.decode(state), context)
      case 2:
        return this._handler2(route2.enc.decode(state), context)
      case 3:
        return this._handler3(route3.enc.decode(state), context)
      case 4:
        return this._handler4(route4.enc.decode(state), context)
      default:
        throw new Error('Handler not found for ID:' + id)
    }
  }
}

function dispatch (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const o = getEncoderAndId(name)
  setVersion(version)

  c.uint.preencode(state, o.id)
  o.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, o.id)
  o.enc.encode(state, message)

  return state.buffer
}

const route0 = {
  id: 0,
  enc: getEncoding('@autopass-namespace/writer')
}

const route1 = {
  id: 1,
  enc: getEncoding('@autopass-namespace/writer')
}

const route2 = {
  id: 2,
  enc: getEncoding('@autopass-namespace/autopass')
}

const route3 = {
  id: 3,
  enc: getEncoding('@autopass-namespace/delete')
}

const route4 = {
  id: 4,
  enc: getEncoding('@autopass-namespace/invite')
}

function getEncoderAndId (name) {
  switch (name) {
    case '@autopass-namespace/removeWriter':
      return route0
    case '@autopass-namespace/addWriter':
      return route1
    case '@autopass-namespace/put':
      return route2
    case '@autopass-namespace/del':
      return route3
    case '@autopass-namespace/addInvite':
      return route4
    default:
      throw new Error('Handler not found for name: ' + name)
  }
}

module.exports = {
  version,
  dispatch,
  Router
}
