// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autopass/records
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (m.value) c.string.preencode(state, m.value)
    if (m.file) c.buffer.preencode(state, m.file)
  },
  encode(state, m) {
    const flags = (m.value ? 1 : 0) | (m.file ? 2 : 0)

    c.string.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.value) c.string.encode(state, m.value)
    if (m.file) c.buffer.encode(state, m.file)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      value: (flags & 1) !== 0 ? c.string.decode(state) : null,
      file: (flags & 2) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @autopass/mirrors
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)

    return {
      key: r0
    }
  }
}

// @autopass/writer
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = (m.name ? 1 : 0) | (m.readOnly ? 2 : 0)

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      readOnly: (flags & 2) !== 0
    }
  }
}

// @autopass/delete
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @autopass/invitee
const encoding4 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = m.name ? 1 : 0

    c.fixed32.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @autopass/public-invite-metadata
const encoding5 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.readOnly ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      readOnly: (flags & 1) !== 0
    }
  }
}

// @autopass/additional-invite-data
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.data)
    c.buffer.preencode(state, m.signature)
  },
  encode(state, m) {
    c.buffer.encode(state, m.data)
    c.buffer.encode(state, m.signature)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      data: r0,
      signature: r1
    }
  }
}

// @autopass/invite.additional
const encoding7_5 = c.frame(encoding6)

// @autopass/invite
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
    state.end++ // max flag is 2 so always one byte

    if (m.additional) encoding7_5.preencode(state, m.additional)
  },
  encode(state, m) {
    const flags = (m.readOnly ? 1 : 0) | (m.additional ? 2 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.additional) encoding7_5.encode(state, m.additional)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      readOnly: (flags & 1) !== 0,
      additional: (flags & 2) !== 0 ? encoding7_5.decode(state) : null
    }
  }
}

// @autopass/del-invite
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @autopass/del-mirror
const encoding9 = encoding1

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@autopass/records':
      return encoding0
    case '@autopass/mirrors':
      return encoding1
    case '@autopass/writer':
      return encoding2
    case '@autopass/delete':
      return encoding3
    case '@autopass/invitee':
      return encoding4
    case '@autopass/public-invite-metadata':
      return encoding5
    case '@autopass/additional-invite-data':
      return encoding6
    case '@autopass/invite':
      return encoding7
    case '@autopass/del-invite':
      return encoding8
    case '@autopass/del-mirror':
      return encoding9
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
