// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

// '@autopass/records' collection key
const collection0_key = new IndexEncoder([IndexEncoder.STRING], { prefix: 0 })

function collection0_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autopass/records' value encoding
const collection0_enc = getEncoding('@autopass/records/hyperdb#0')

// '@autopass/records' reconstruction function
function collection0_reconstruct(version, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection0_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@autopass/records' key reconstruction function
function collection0_reconstruct_key(keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autopass/records'
const collection0 = {
  name: '@autopass/records',
  id: 0,
  encodeKey(record) {
    const key = [record.key]
    return collection0_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection0_enc, record)
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: []
}

// '@autopass/invite' collection key
const collection1_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 1 })

function collection1_indexify(record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@autopass/invite' value encoding
const collection1_enc = getEncoding('@autopass/invite/hyperdb#1')

// '@autopass/invite' reconstruction function
function collection1_reconstruct(version, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection1_enc, valueBuf)
  record.id = key[0]
  return record
}
// '@autopass/invite' key reconstruction function
function collection1_reconstruct_key(keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@autopass/invite'
const collection1 = {
  name: '@autopass/invite',
  id: 1,
  encodeKey(record) {
    const key = [record.id]
    return collection1_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection1_enc, record)
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: []
}

// '@autopass/mirrors' collection key
const collection2_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 2 })

function collection2_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autopass/mirrors' value encoding
const collection2_enc = getEncoding('@autopass/mirrors/hyperdb#2')

// '@autopass/mirrors' reconstruction function
function collection2_reconstruct(version, keyBuf, valueBuf) {
  const key = collection2_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection2_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@autopass/mirrors' key reconstruction function
function collection2_reconstruct_key(keyBuf) {
  const key = collection2_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autopass/mirrors'
const collection2 = {
  name: '@autopass/mirrors',
  id: 2,
  encodeKey(record) {
    const key = [record.key]
    return collection2_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection2_key.encodeRange({
      gt: gt ? collection2_indexify(gt) : null,
      lt: lt ? collection2_indexify(lt) : null,
      gte: gte ? collection2_indexify(gte) : null,
      lte: lte ? collection2_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection2_enc, record)
  },
  trigger: null,
  reconstruct: collection2_reconstruct,
  reconstructKey: collection2_reconstruct_key,
  indexes: []
}

// '@autopass/writer' collection key
const collection3_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 3 })

function collection3_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autopass/writer' value encoding
const collection3_enc = getEncoding('@autopass/writer/hyperdb#3')

// '@autopass/writer' reconstruction function
function collection3_reconstruct(version, keyBuf, valueBuf) {
  const key = collection3_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection3_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@autopass/writer' key reconstruction function
function collection3_reconstruct_key(keyBuf) {
  const key = collection3_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autopass/writer'
const collection3 = {
  name: '@autopass/writer',
  id: 3,
  encodeKey(record) {
    const key = [record.key]
    return collection3_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection3_key.encodeRange({
      gt: gt ? collection3_indexify(gt) : null,
      lt: lt ? collection3_indexify(lt) : null,
      gte: gte ? collection3_indexify(gte) : null,
      lte: lte ? collection3_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection3_enc, record)
  },
  trigger: null,
  reconstruct: collection3_reconstruct,
  reconstructKey: collection3_reconstruct_key,
  indexes: []
}

// '@autopass/delete' collection key
const collection4_key = new IndexEncoder([IndexEncoder.STRING], { prefix: 4 })

function collection4_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autopass/delete' value encoding
const collection4_enc = getEncoding('@autopass/delete/hyperdb#4')

// '@autopass/delete' reconstruction function
function collection4_reconstruct(version, keyBuf, valueBuf) {
  const key = collection4_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection4_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@autopass/delete' key reconstruction function
function collection4_reconstruct_key(keyBuf) {
  const key = collection4_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autopass/delete'
const collection4 = {
  name: '@autopass/delete',
  id: 4,
  encodeKey(record) {
    const key = [record.key]
    return collection4_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection4_key.encodeRange({
      gt: gt ? collection4_indexify(gt) : null,
      lt: lt ? collection4_indexify(lt) : null,
      gte: gte ? collection4_indexify(gte) : null,
      lte: lte ? collection4_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection4_enc, record)
  },
  trigger: null,
  reconstruct: collection4_reconstruct,
  reconstructKey: collection4_reconstruct_key,
  indexes: []
}

// '@autopass/del-invite' collection key
const collection5_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 5 })

function collection5_indexify(record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@autopass/del-invite' value encoding
const collection5_enc = getEncoding('@autopass/del-invite/hyperdb#5')

// '@autopass/del-invite' reconstruction function
function collection5_reconstruct(version, keyBuf, valueBuf) {
  const key = collection5_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection5_enc, valueBuf)
  record.id = key[0]
  return record
}
// '@autopass/del-invite' key reconstruction function
function collection5_reconstruct_key(keyBuf) {
  const key = collection5_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@autopass/del-invite'
const collection5 = {
  name: '@autopass/del-invite',
  id: 5,
  encodeKey(record) {
    const key = [record.id]
    return collection5_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection5_key.encodeRange({
      gt: gt ? collection5_indexify(gt) : null,
      lt: lt ? collection5_indexify(lt) : null,
      gte: gte ? collection5_indexify(gte) : null,
      lte: lte ? collection5_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection5_enc, record)
  },
  trigger: null,
  reconstruct: collection5_reconstruct,
  reconstructKey: collection5_reconstruct_key,
  indexes: []
}

// '@autopass/del-mirror' collection key
const collection6_key = new IndexEncoder([IndexEncoder.BUFFER], { prefix: 6 })

function collection6_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@autopass/del-mirror' value encoding
const collection6_enc = getEncoding('@autopass/del-mirror/hyperdb#6')

// '@autopass/del-mirror' reconstruction function
function collection6_reconstruct(version, keyBuf, valueBuf) {
  const key = collection6_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection6_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@autopass/del-mirror' key reconstruction function
function collection6_reconstruct_key(keyBuf) {
  const key = collection6_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@autopass/del-mirror'
const collection6 = {
  name: '@autopass/del-mirror',
  id: 6,
  encodeKey(record) {
    const key = [record.key]
    return collection6_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection6_key.encodeRange({
      gt: gt ? collection6_indexify(gt) : null,
      lt: lt ? collection6_indexify(lt) : null,
      gte: gte ? collection6_indexify(gte) : null,
      lte: lte ? collection6_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection6_enc, record)
  },
  trigger: null,
  reconstruct: collection6_reconstruct,
  reconstructKey: collection6_reconstruct_key,
  indexes: []
}

const collections = [
  collection0,
  collection1,
  collection2,
  collection3,
  collection4,
  collection5,
  collection6
]

const indexes = []

module.exports = {
  version,
  collections,
  indexes,
  resolveCollection,
  resolveIndex
}

function resolveCollection(name) {
  switch (name) {
    case '@autopass/records':
      return collection0
    case '@autopass/invite':
      return collection1
    case '@autopass/mirrors':
      return collection2
    case '@autopass/writer':
      return collection3
    case '@autopass/delete':
      return collection4
    case '@autopass/del-invite':
      return collection5
    case '@autopass/del-mirror':
      return collection6
    default:
      return null
  }
}

function resolveIndex(name) {
  switch (name) {
    default:
      return null
  }
}
